# This is a basic workflow to help you get started with Actions

name: Java CI with Gradle

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Running Java Compile
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with: 
            java-version: '1.8'
            cache: 'gradle'
      #更改脚本权限
      - name: Grant execute permission for gradlew  
        run: chmod +x gradlew
      # Runs a set of commands using the runners shell
      - name: Run gradle build
        run: ./gradlew build --no-daemon
